### ISSUE TITLE
Tests break since zope.app.wsgi >= 5.2

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.app.publisher#18]
### What I did:

Run the tests in GHA and locally.

### What I expect to happen:

Green tests.

### What actually happened:

Expat parsing errors.
e. g. https://github.com/zopefoundation/zope.app.publisher/actions/runs/11764975438/job/32770761496 

### What version of Python and Zope/Addons I am using:

zope.app.publisher == `master`
zope.app.wsgi == 5.2 (with older versions the tests still pass)
any supported Python version

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2024-11-11 23:56 -0800:
>## PROBLEM REPORT
>### What I did:
>
>Run the tests in GHA and locally.
>
>### What I expect to happen:
>
>Green tests.
>
>### What actually happened:
>
>Expat parsing errors.
>e. g. https://github.com/zopefoundation/zope.app.publisher/actions/runs/11764975438/job/32770761496

The problem is again a wrong `Content-Length` value:
because `multipart 1.1+` insists (at some places) on HTTP compatible
`\r\n` line endings, we have changed `\n` line endings
into `\r\n` in `zope.app.wsgi`. But, such a change increases the
"content-length".

I see foor approaches:

 1. we fix the `Content-Length` in the failing tests to make
    them fit the `\n` -> `\r\n` change performed internally

 2. we drop the `Content-Length` header in the failing tests

 3. we change the tests to use `\r\n` line endings in the first
    place and use the corresponding `Content-Length` value

 4. we fix a `Content-Length` request header in `zope.app.wsgi`
    when it has changed the line endings

I do not think 1 is good, because a careful test observer would
find a `Content-Length`/visible content length discrepancy.


My personal preference is 4.

4 would remove `Content-Length` replated problems for other
users of `zope.app.wsgi` as well but require another `zope.app.wsgi`
release.
In such a release we could fix another problem:
line ending replacement is necessary for `multipart` but
not a good idea for e.g. binary request bodies (where line endings
should not get changed).
I therefore propose to let `zope.app.wsgi` only change the line
endings for `multipart/form-data` requests (the only case
when `multipart` requires `\r\n` line endings) and then
adjust `Content-Length` automatically.

**Comment by icemac** [comment]
I tried setting content_lentgth in `zope.app.wsgi` but it did not help. Even though `zope.app.wsgi.testlayer.http` was actually called. But maybe I tried it too naively.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2024-11-13 00:18 -0800:
>I tried setting content_lentgth in `zope.app.wsgi` but it did not help. Even though `zope.app.wsgi.testlayer.http` was actually called. But maybe I tried it too naively.

It is not trivial.

I would try it the following way:
 * check if there is a `Content-Length` header, if not do not
   add one
 * use `Content-Length` to split the request into the request headers
   and the request body.
   Transform line endings `\n` -> `\r\n` in the request body
   and update `Content-Length` with the resulting length.

   We may or may not transform the line endings for the headers, too.
   `multipart` has no specific requirements regarding them

To fix the second problem "do not change anything for binary
request bodies", I suggest to make line ending replacements
only for `multipart/form-data` requests.
Those are the only requests for which `multipart` insists on
`\r\n` line endings. We could in addition limit the replacement
to `POST` requests, but likely this is not necessary.


There will still be one case where test failures may occur:
we only change the request for textual (`str`, `bytes`) input,
not for file like input.
Should there be such tests, I suggest to make the line ending
substitution directly there (before the input is wrapped into a file like
object).


If you want, I can make a `zope.app.wsgi` PR implementing my
proposal.

**Comment by d-maurer** [comment]
***@***.*** wrote at 2024-11-13 09:37 +0100:
>Michael Howitz wrote at 2024-11-13 00:18 -0800:
> ...
>It is not trivial.
> ...
>To fix the second problem "do not change anything for binary
>request bodies", I suggest to make line ending replacements
>only for `multipart/form-data` requests.
>Those are the only requests for which `multipart` insists on
>`\r\n` line endings. We could in addition limit the replacement
>to `POST` requests, but likely this is not necessary.

This is still not fully right:
`multipart/form-data` bodies may contain binary parts
which we must not change. Likely, only the top level
`multipart/form-data` structure should be changed
and, when I remember right, the `\r\n` line ending is necessary
only for the boundary lines.

I tend to withdraw my previous suggestion to make the `multipart>=1.1.`
adaptation in `zope.app.wsgi`.
Instead, we likely should make the adaptation in the individual tests.

**Comment by d-maurer** [comment]
@icemac 
Having been wrong several times in this discussion, I made a thorough analysis.
Relevant is the [mutipart stardard](https://datatracker.ietf.org/doc/html/rfc2046#section-5.1). It essentially requires that the multipart parts use CRLF as line separator both for their header as well as for the multipart boundary. In this, the multipart boundary starts and ends with a line separator; the starting one is considered part of the boundary, not of the preceding body.
If we change the line separator also in the part body, we risk to change its value.

`multipart==1.1` mostly follows the standard (the standard allows whitespace before the closing boundary line separator, `multipart` does not).
As a consequence, we must use CRLF line separators in multipart part headers and boundaries; we must not change anything in part bodies.

If we want to handle those requirements automatically in `zope.app.wsgi`, we should change line separators only for `multipart/form-data` requests. We would then need to parse the multipart body to separate the part bodies from the remaining multipart body, the main task we use `multipart` for. But, if we need our own multipart parsing implementation, why not use it everywhere instead of `multipart`?


In view of these analysis results, I think my previous proposal to prevent the test failures by a change in `zope.app.wsgi` has been wrong. We should revert the corresponding `zope.app.wsgi` modifications and fix failing tests by making them compatible with the multipart standard (i.e. by directly using the correct line separators).

**Comment by mgedmin** [comment]
Since zope.app.publisher itself is not responsible for parsing the multipart/form-data structure, perhaps its tests should be written using a higher abstraction level?  Could we use WebTest or something like that, instead of worrying about line ending characters in string literals in the test cases?

**Comment by d-maurer** [comment]
Marius Gedminas wrote at 2024-11-16 04:30 -0800:
>Since zope.app.publisher itself is not responsible for parsing the multipart/form-data structure, perhaps its tests should be written using a higher abstraction level?  Could we use WebTest or something like that, instead of worrying about line ending characters in string literals in the test cases?

I think something like this has been the reasoning behind using
`zope.app.wsig.testing.http`. But, that latter is not sufficuently
intelligent.
Your idea may thus be a good alternative!

**Comment by icemac** [comment]
I created https://github.com/zopefoundation/zope.app.wsgi/pull/30 to revert the changes in `zope.app.wsgi`.

**Comment by icemac** [comment]
I released a new version of `zope.app.wsgi` including https://github.com/zopefoundation/zope.app.wsgi/pull/30. This fixed our tests here (but will break them elsewhere).

Thank you for your investigation.
